version: 2

before:
  hooks:
    - go mod tidy

builds:
  - goos:
      - 'darwin'
    ldflags:
      - -s -w -X github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}/cmd.version={{ .Version }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{.Tag}}"
    directory: Formula
    caveats: |
        Please check usage at README:
            https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}/blob/main/README.md
    homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
    description: |
      {{ .Env.DESCRIPTION }}
    license: MIT
    skip_upload: auto
    dependencies:
      - name: reminders-cli
        os: mac
    service: |
      run [opt_bin/"{{ .ProjectName }}", "serve"]
      keep_alive true
      log_path var/"log/{{ .ProjectName }}.log"
      error_log_path var/"log/{{ .ProjectName }}.log"
    test: |
      system "#{bin}/{{ .ProjectName }} --help"
    repository:
      owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
      name: "{{ .Env.HOMEBREW_REPO_NAME }}"
      branch: main
